name: FreeXCraft Auto Renew

on:
  schedule:
    - cron: '5 */4 * * *'
  workflow_dispatch: # 手动触发按钮

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Smart Run (Immediate for Manual, Random for Auto)
        env:
          FXC_EMAIL: ${{ secrets.FXC_EMAIL }}
          FXC_PASS: ${{ secrets.FXC_PASS }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          # 检查触发事件的类型
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "🚀 检测到手动触发，跳过延迟，立即执行续期！"
            python renew.py
          else
            delay=$((1 + RANDOM % 3600))
            printdate=$(date -d "+8 hours" "+%Y-%m-%d %H:%M:%S")
            echo "⏰ 定时任务触发 (北京时间: $printdate)"
            echo "💤 为了模拟真人，将随机等待 $delay 秒..."
            sleep $delay
            python renew.py
          fi
