name: FreeXCraft Auto Renew

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:       # 允许手动运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install requests
      - name: Run Script
        env:
          FXC_EMAIL: ${{ secrets.FXC_EMAIL }}
          FXC_PASS: ${{ secrets.FXC_PASS }}
        run: python renew.py
